# -*- coding: utf-8 -*-
"""live speech to text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MW3mWIPmpxrxwqPRPBoJwDYsSeszcvwx
"""

!pip install PyAudio

pip install SpeechRecognition

import speech_recognition as sr

r=sr.Recognizer()

with sr.Microphone() as source:
  print("say something")
  audio_text=r.listen(source)
  print('stop, thank you')

try:
  print("text:"+|r.recognize_google(audio_text))
except:
  print("please, try again")